=== TheBestAzir/xml-c-plus-plus/hh.dtd
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE Library[
<!ELEMENT Library(Book,Member)>
<!ELEMENT Book (Title,Author,Price,Publisher,Cost)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Publisher (#PCDATA)>
<!ELEMENT Cost (#PCDATA)>
<!ELEMENT Member (Name,Address)>
<!ELEMENT Name (FirtName,MiddleName,LastName)>
<!ELEMENT FirtName (#PCDATA)>
<!ELEMENT MiddleName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT Address (HouseNumber,Street,City)>
<!ELEMENT HouseNumber (#PCDATA)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ATTLIST Book Bookid ID #REQUIRED>
]>

=== TheBestAzir/xml-c-plus-plus/zr.xml
<?xml version="1.0" encoding="UTF-8"?>  
<!DOCTYPE Library SYSTEM "hh.dtd">
<Library>
<Book Bookid="12">
<Title>朝花夕拾</Title>
<Author>鲁迅</Author>
<Price>30元</Price>
<Publisher>人民教育出版社</Publisher>
<Cost>2</Cost>
</Book>
<Member>
<Name>
<FirstName>q</FirstName>
<MiddleName>w</MiddleName>
<LastName>e</LastName>
</Name>
<Address>
<HouseNumber>7</HouseNumber>
<Street>8</Street>
<City>9</City>
</Address>
</Member>
</Library>
